### ISSUE TITLE
unable to download parse-srcset from github

### ISSUE THREAD

**Issue by cdaringe** [brody2consult/prettierx#167]
# problem

i use a private npm registry, but parse-srcset is getting pulled from github, which is offlimits in my CI env 😭 

https://github.com/brodybits/prettierx/blob/425d40c9ed0ba7e3ddaabdc7ac54454fd3e6c52a/package.json#L64

# discussion

could we move this to an npm hosted version of srcset, or do we really need a particular sha? perhaps a npm publish could be acheived?

**Comment by brody2consult** [comment]
This dependency comes from the upstream prettier/prettier project, and the npm hosted version will come in when prettier@2.0.0 is merged in. I can try to update it more quickly, no promise though.

**Comment by brody2consult** [comment]
I was able to update it on the default `dev` branch, will be part of 0.11.2 patch release. I will try to avoid this kind of github dependency in the future. Thanks again for reporting.

**Comment by cdaringe** [comment]
Awesome thank you!
