### ISSUE TITLE
Bug with selfclosing JSX and comments in TS ?

### ISSUE THREAD

**Issue by aMarCruz** [brody2consult/prettierx#26]
Hi @brodybits ,
I have an issue after upgrading my eslint-plugin-prettierx to prettierx 0.7 that cannot be reproduced in the Prettier playground.
In this fragment the JSDoc comment is marked for deletion:

![image](https://user-images.githubusercontent.com/6636980/60143834-b84cdb80-9785-11e9-93d8-258dc4517036.png)

Have you seen something like this before?

The error is present with ESLint 5.16 and 6.0, with @typescript-eslint/parser 1.9 and 1.11

This is the config of prettierx:

```json
{
  "alignTernaryLines": false,
  "arrowParens": "avoid",
  "bracketSpacing": true,
  "endOfLine": "lf",
  "generatorStarSpacing": true,
  "indentChains": true,
  "jsxBracketSameLine": false,
  "jsxSingleQuote": false,
  "printWidth": 92,
  "quoteProps": "consistent",
  "semi": false,
  "singleQuote": true,
  "spaceBeforeFunctionParen": true,
  "trailingComma": "es5",
  "yieldStarSpacing": true,
  "overrides": [
    {
      "files": "src/lib/toPlainLowerCase.ts",
      "options": {
        "printWidth": 320
      }
    }
  ]
}
```

It is not happening if `<Card contact={contact} />` is closed: `<Card contact={contact}></Card>`, but prettierx removes `</Card>` forcing to selfclose.

Any help is appreciated. Thanks.

**Comment by brody2consult** [comment]
Test case would be appreciated. Sorry I missed it before.

**Comment by brody2consult** [comment]
My bad, test case was already in the description (image). Adding the bug label until I get a chance to investigate. I think we should also add a new test case to the existing test suite to avoid this kind of an issue in the future.

**Comment by brody2consult** [comment]
I tried this code with both `--parser=babel-ts` and `--parser=typescript` and it seems to be OK:

```typescript
import React from 'react'

type Contact = { name: string }

const Card = (props: { contact: Contact }) => <div>{props.contact.name}</div>

/**
 * Comment here
 */
export const ContactsBar = (contacts: Contact[]) => <div>{contacts.map(renderCard)}</div>
```

Closing for now. Please report if you still see an issue with JSX, comments, and TypeScript.

**Comment by aMarCruz** [comment]
Thanks!!
