### ISSUE TITLE
bracketSpacing and compatibility with Prettier configs

### ISSUE THREAD

**Issue by aMarCruz** [brody2consult/prettierx#462]
Lack of the `bracketSpacing` option in PrettierX breaks compatibility with Prettier configs.

This configuration with Prettier...

```
{
  "bracketSpacing": false,
}
```

Does not work with PrettierX.
I think the compatibility should be preserved by expanding `bracketSpacing` in its equivalent grainy options.

**Comment by brody2consult** [comment]
Thanks.

I raised <https://github.com/prettier/prettier/issues/10008> with the complaint that `--no-bracket-spacing` option is confusing and got the following response in <https://github.com/prettier/prettier/issues/10008#issuecomment-755039026>:

> I say we should remove this option from the documentation , no one should use it. I remember I suggested to remove it, but rejected ~for some reason, I can't find that issue~ #7841.

Digging back through the links, I think this was the most important rationale for not removing `--no-bracket-spacing` from Prettier: <https://github.com/prettier/prettier/issues/3503#issuecomment-352184519>

> Facebook uses `no-bracket-spacing`, and it's actually kind of growing on me.

Any real-world examples of Prettier configs that are broken by this update would be really helpful.

I did find this update where you updated a number of the options 👍 <https://github.com/aMarCruz/eslint-plugin-prettierx/commit/67e1c5472e9c49a7c93ffcd55313a65d83463d89>

**Comment by brody2consult** [comment]
Now I have a better idea where you may have been coming from. I noticed in <https://github.com/aMarCruz/eslint-plugin-prettierx/commit/67e1c5472e9c49a7c93ffcd55313a65d83463d89> that you have been configuring and documenting all relevant options in Prettier & prettierX.

That said, I am still pretty reluctant to support `bracketSpacing` again due to the burden of updating the code, testing, and support.

**Comment by aMarCruz** [comment]
@brodybits ,
I like the granular options in prettierx v17.
The only downside is that unsupported options causes prettierx loading to fail.
(See aMarCruz/eslint-plugin-prettierx#7)
As always, thanks for your prompt reply.
Closing.

**Comment by brody2consult** [comment]
> (See [aMarCruz/eslint-plugin-prettierx#7](https://github.com/aMarCruz/eslint-plugin-prettierx/issues/7))

Got it, wish you would have mentioned it before. Definitely was a **breaking** change:)

**Comment by aMarCruz** [comment]
> > (See [aMarCruz/eslint-plugin-prettierx#7](https://github.com/aMarCruz/eslint-plugin-prettierx/issues/7))
> 
> Got it, wish you would have mentioned it before. Definitely was a **breaking** change:)

Yep, `bracketSpacing` should be a no-op.
Thanks!
