### ISSUE TITLE
disabled space-before-function-paren adds a space between generic and function paren

### ISSUE THREAD

**Issue by havenchyk** [brody2consult/prettierx#52]
*Edited, initial version was not correct*

I came across the weird and likely wrong behavior with formatting of the next lines of code

```
function foo<T>(x: T): T {
  return x
}
```
 
Even if I **don't** pass `--space-before-function-paren` flag (default value is false), space is added between `foo<T extends number>` and `(x: T)`,

so the result is:

```
function foo<T> (x: T): T { // <-- space between <T> and (x: T)
  return T
}
```

Could you please confirm it's an issue?

**Comment by brody2consult** [comment]
I think this feature is working as intended. Space does come before the function paren in the formatted code.

And I get the same results when using eslint with the following settings in `.eslintrc.yml` config:
- `parser: '@typescript-eslint/parser'`
- `space-before-function-paren: ["error", "always"]` in rules

In case you are looking for something different, please give some more details about what you are looking for, if you can find an existing eslint rule that would support the desired formatting, and what kind of justification you can find. Contributions are always welcome for consideration.

I am not in a position to make any promises within the standard free support on GitHub but would be happy to discuss and consider supporting this kind of feature for hire. Please contact <sales@brodysoft.com> in case of any interest.

**Comment by havenchyk** [comment]
@brodybits seems I mixed up everything, let me try once again.

with ` --space-before-function-paren` this space *should* be added, so next example is correct

```
function foo<T> (x: T): T { // <-- space between <T> and (x: T)
  return x
}
```

but the default value for `--space-before-function-paren` is `false` and if I don't pass it, I expect to receive

```
function foo<T>(x: T): T { // <-- no space between <T> and (x: T)
  return x
}
```

and it's exactly what eslint does with the rule you mentioned:

> And I get the same results when using eslint with the following settings in .eslintrc.yml config:
> parser: '@typescript-eslint/parser'
> space-before-function-paren: ["error", "always"] in rules

But prettierx adds this space anyway, disregarding flag value.

Hope it's a better explanation. And if you confirm it's a wrong behavior I'm ready to help with it

**Comment by brody2consult** [comment]
I still do not see your issue. Here is what I tried:

Taking the following TypeScript that I saved as `example.ts`:

```ts
function foo<T> (x: T): T {
  return x
}
```

Tried with prettier version `1.19.1`: `prettier example.ts > fix1.ts`, here is the result:

```ts
function foo<T>(x: T): T {
  return x;
}
```

Next try with prettierx version `0.10.0`, along with TypeScript 3.7.2 which is no longer bundled: `prettierx example.ts > fix2.ts` gives me this result:

```ts
function foo<T>(x: T): T {
  return x;
}
```

And another test: `prettierx --space-before-function-paren example.ts` gives me:

```ts
function foo<T> (x: T): T {
  return x;
}
```

And then still the same results if I would do `cp example.ts example.js` and try the same things on the JavaScript files.

**Comment by havenchyk** [comment]
@brodybits my bad. I was sure that prettier-standard just uses `prettierx` for formatting, but seems it's not only `prettierx`. So even old (0.7.1) version works correctly.

The correct version of broken code is 

```
const foo = function<T>(bar: T) {
  return bar
}
```

prettier-standard adds a space between `<T>` and `(bar: T)`, prettierx handles this correctly.

Sorry for bothering you @brodybits and thanks for you help! 

btw, I see that `prettierx` even supports optional chaining in latest version 👏

**Comment by havenchyk** [comment]
@brodybits new info came.

```
import prettierx from 'prettierx'

const options = {
  spaceBeforeFunctionParen: false,
  generatorStarSpacing: true,
  yieldStarSpacing: true,
  singleQuote: true,
  semi: false,
  jsxSingleQuote: true,
  useTabs: true,
  endOfLine: 'lf',
  filepath: '/Users/havenchyk/projects/test-prettierx/index.ts',
  parser: 'typescript'
}

const text = 'const foo = function<T>(bar: T) { return bar }'

const formatted = prettierx.format(text, options)

console.log(formatted)

/**
 * const foo = function<T> (bar: T) {
 *   return bar
 * }
 */
```

Tried it with version `0.10`. Am I doing formatting wrong? I'm also surprised it's different from the result from CLI

**Comment by brody2consult** [comment]
Thanks @havenchyk, I added the bug label with **help wanted** for now. A new test case would be very helpful.
