### ISSUE TITLE
Error: unknown type: "TSNamedTupleMember"

### ISSUE THREAD

**Issue by adalinesimonian** [brody2consult/prettierx#548]
prettierx errors out when linting typescript files with named tuples.

This bug was ironed out in https://github.com/prettier/prettier/pull/8885 last August. However, this bug fix, along with others, has not yet been merged into prettierx. prettier is currently at version 2.3.0, released 12 days ago at the time of this post, and this particular fix was merged just before the release of 2.1.0 in August.

Related to #414

**Comment by adalinesimonian** [comment]
Opened draft PR in #549, working on merging prettier 2.3.0 into prettierx, which includes fixes for typescript

**Comment by brody2consult** [comment]
This should be resolved now that we have merged the updates from Prettier 2.3.2.
