### ISSUE TITLE
[prettierx] option to keep imports on a single line

### ISSUE THREAD

**Issue by brody2consult** [brody2consult/prettierx#68]
idea from prettier/prettier#5995

I am downvoting this idea due to personal bias (yes, downvoting my own issue), raising it for the sake of tracking and possible discussion.

**Comment by EtienneBourque** [comment]
Isn't the point of PrettierX to be a less opiniated version of Prettier? If so, what's the downside to have an additional option, knowing that if we wanted an ultra rigid formatter, there is already Prettier.
